import type { MetadataRoute } from "next";
import { asc, eq } from "drizzle-orm";
import { db } from "@/db";
import { products } from "@/db/schema";
import { products as staticProducts } from "@/lib/products";

// Refresh hourly so new/edited products are picked up without redeploys.
export const revalidate = 3600;

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL ?? "https://www.goldinterestofficial.com";

// <sitemap-lastmod:start> — auto-generated by `npm run sitemap:dates`. Do not edit by hand.
// Last content change per static route (YYYY-MM-DD, from git history).
// Product dates resolve live from the DB; STATIC_CATALOG_LASTMOD is the
// last resort for the built-in catalog when the DB is unreachable.
const LASTMOD: Record<string, string> = {
  "/": "2026-09-15",
  "/shop": "2026-09-15",
  "/privacy": "2026-09-15",
  "/returns": "2026-09-15",
  "/shipping": "2026-09-15",
  "/terms": "2026-09-15",
};
const STATIC_CATALOG_LASTMOD = "2026-09-15";
// <sitemap-lastmod:end>

const isAbsoluteHttp = (u: string) => /^https?:\/\//i.test(u);
// Strip query strings (?w=800&auto=format…) so <image:loc> stays valid,
// escapable XML and points at the canonical image URL.
const canonicalImage = (u: string) => u.split("?")[0];

type ProductEntry = { slug: string; lastmod: string; image?: string };

async function productEntries(): Promise<ProductEntry[]> {
  try {
    if (db) {
      const rows = await db
        .select({ slug: products.slug, updatedAt: products.updatedAt, images: products.images })
        .from(products)
        .where(eq(products.active, true))
        .orderBy(asc(products.createdAt));
      if (rows.length > 0) {
        return rows.map((r) => {
          const imgs = (r.images as string[] | null) ?? [];
          const raw = imgs.find(isAbsoluteHttp);
          return {
            slug: r.slug,
            lastmod: r.updatedAt
              ? new Date(r.updatedAt).toISOString().slice(0, 10)
              : STATIC_CATALOG_LASTMOD,
            image: raw ? canonicalImage(raw) : undefined,
          };
        });
      }
    }
  } catch {
    // Fall through to the built-in catalog below.
  }
  return staticProducts.map((p) => {
    const raw = p.images.find(isAbsoluteHttp);
    return { slug: p.slug, lastmod: STATIC_CATALOG_LASTMOD, image: raw ? canonicalImage(raw) : undefined };
  });
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const entries = await productEntries();

  const productUrls: MetadataRoute.Sitemap = entries.map((p) => ({
    // encodeURI: stored slugs predate URL-safe enforcement and may contain
    // spaces — a raw space in <loc> is invalid XML and breaks crawlers.
    url: encodeURI(`${siteUrl}/product/${p.slug}`),
    lastModified: p.lastmod,
    changeFrequency: "weekly",
    priority: 0.8,
    ...(p.image ? { images: [p.image] } : {}),
  }));

  return [
    { url: `${siteUrl}/`, lastModified: LASTMOD["/"], changeFrequency: "daily", priority: 1 },
    { url: `${siteUrl}/shop`, lastModified: LASTMOD["/shop"], changeFrequency: "weekly", priority: 0.9 },
    ...productUrls,
    { url: `${siteUrl}/privacy`, lastModified: LASTMOD["/privacy"], changeFrequency: "monthly", priority: 0.6 },
    { url: `${siteUrl}/returns`, lastModified: LASTMOD["/returns"], changeFrequency: "monthly", priority: 0.6 },
    { url: `${siteUrl}/shipping`, lastModified: LASTMOD["/shipping"], changeFrequency: "monthly", priority: 0.6 },
    { url: `${siteUrl}/terms`, lastModified: LASTMOD["/terms"], changeFrequency: "monthly", priority: 0.6 },
  ];
}
