#!/usr/bin/env python3
"""Refresh the <lastmod> dates in app/sitemap.ts from git history.

Usage:  npm run sitemap:dates   (or: python3 scripts/refresh-sitemap-dates.py)

For each static route it takes the last commit date of its page file
(`git log -1 --format=%cs`), falling back to the file's mtime and then
today. It rewrites only the block between the
<sitemap-lastmod:start> / <sitemap-lastmod:end> markers, so hand-written
code around it is never touched. Run it after editing page copy, then
commit the result.
"""

import datetime
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITEMAP = os.path.join(ROOT, "app", "sitemap.ts")

# route -> page file (relative to repo root)
ROUTES = {
    "/": "app/page.tsx",
    "/shop": "app/shop/page.tsx",
    "/privacy": "app/privacy/page.tsx",
    "/returns": "app/returns/page.tsx",
    "/shipping": "app/shipping/page.tsx",
    "/terms": "app/terms/page.tsx",
}
STATIC_CATALOG_FILE = "lib/products.ts"


def date_for(path: str) -> str:
    full = os.path.join(ROOT, path)
    try:
        out = subprocess.run(
            ["git", "log", "-1", "--format=%cs", "--", path],
            cwd=ROOT,
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        if re.fullmatch(r"\d{4}-\d{2}-\d{2}", out):
            return out
    except (subprocess.CalledProcessError, FileNotFoundError):
        pass
    if os.path.exists(full):  # fallback: filesystem mtime
        return datetime.date.fromtimestamp(os.path.getmtime(full)).isoformat()
    print(f"warning: no date source for {path}, using today", file=sys.stderr)
    return datetime.date.today().isoformat()


def main() -> None:
    with open(SITEMAP, encoding="utf-8") as f:
        src = f.read()

    lines = ['"{}": "{}",'.format(route, date_for(path)) for route, path in ROUTES.items()]
    block = (
        "// <sitemap-lastmod:start> — auto-generated by `npm run sitemap:dates`. Do not edit by hand.\n"
        "// Last content change per static route (YYYY-MM-DD, from git history).\n"
        "// Product dates resolve live from the DB; STATIC_CATALOG_LASTMOD is the\n"
        "// last resort for the built-in catalog when the DB is unreachable.\n"
        "const LASTMOD: Record<string, string> = {\n"
        + "".join(f"  {line}\n" for line in lines)
        + "};\n"
        f'const STATIC_CATALOG_LASTMOD = "{date_for(STATIC_CATALOG_FILE)}";\n'
        "// <sitemap-lastmod:end>"
    )

    pattern = re.compile(r"// <sitemap-lastmod:start>.*// <sitemap-lastmod:end>", re.DOTALL)
    if not pattern.search(src):
        print("error: markers not found in app/sitemap.ts", file=sys.stderr)
        sys.exit(1)

    with open(SITEMAP, "w", encoding="utf-8") as f:
        f.write(pattern.sub(block, src))
    print("sitemap dates refreshed from git history.")


if __name__ == "__main__":
    main()
